image: docker:git

stages:
  - build
  - cleanup

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  BUILD_NUM_TAG: b$CI_PIPELINE_ID

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker image build --pull -t "$IMAGE_NAME:$BUILD_NUM_TAG" -t $IMAGE_NAME .
    - docker image push "$IMAGE_NAME:$BUILD_NUM_TAG"
    - docker image push $IMAGE_NAME
  only:
    - master

clean:
  stage: cleanup
  script:
    docker image rm -f $(docker image inspect -f '{{.Id}}' "$IMAGE_NAME:$BUILD_NUM_TAG")
  when: always
